complete -c git-svn -a clone 					-d "Initialize and fetch revisions"
complete -c git-svn -a commit-diff 		-d "Commit a diff between two trees"
complete -c git-svn -a create-ignore 	-d "Create a .gitignore per svn:ignore"
complete -c git-svn -a dcommit 				-d "Commit several diffs to merge with upstream"
complete -c git-svn -a fetch 					-d "Download new revisions from Subversion"
complete -c git-svn -a find-rev 			-d "Translate between Subversion revision numbers and tree-ish"
complete -c git-svn -a info 					-d "Show info about the latest Subversion revision"
complete -c git-svn -a init 					-d "Initialize a repo for tracking (requires URL argument)"
complete -c git-svn -a log 						-d "Show commit logs"
complete -c git-svn -a migrate 				-d "Migrate configuration/metadata/layout from previous versions of git-svn"
complete -c git-svn -a propget 				-d "Print the value of a property on a file or directory"
complete -c git-svn -a proplist 			-d "List all properties of a file or directory"
complete -c git-svn -a rebase 				-d "Fetch and rebase your working directory"
complete -c git-svn -a set-tree 			-d "Set a Subversion repository to a git tree-ish"
complete -c git-svn -a show-externals -d "Show svn:externals listings"
complete -c git-svn -a show-ignore 		-d "Show svn:ignore listings"
